# Generated by Django 3.1.7 on 2021-03-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='id',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruit_app.user'),
            preserve_default=False,
        ),
    ]
