# Generated by Django 3.1.7 on 2021-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0003_auto_20210312_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='Psid',
            field=models.IntegerField(null=True),
        ),
    ]
