# Generated by Django 3.1.7 on 2021-03-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0007_panelistschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanelistSchedule',
        ),
    ]
