# Generated by Django 3.1.7 on 2021-03-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0010_interviewschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewSchedule',
        ),
    ]
