# Generated by Django 3.1.7 on 2021-03-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0011_delete_interviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=20)),
                ('interview_time', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit_app.candidate')),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit_app.panelist')),
            ],
        ),
    ]
