# Generated by Django 3.1.7 on 2021-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0012_interviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelistschedule',
            name='Slot_type',
            field=models.CharField(default='AVAILABLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='panelistschedule',
            name='Available_till',
            field=models.DateTimeField(editable=False),
        ),
    ]
