# Generated by Django 3.1.7 on 2021-03-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0013_auto_20210323_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Account',
            field=models.CharField(choices=[('QVC', 'QVC'), ('FINASTRA', 'FINASTRA'), ('BLACKROCK', 'BLACKROCK'), ('GOLDMANSACHS', 'GOLDMANSACHS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Final_status',
            field=models.CharField(choices=[('SELECTED', 'SELECTED'), ('REJECTED', 'REJECTED'), ('OFFER RELEASED', 'OFFER RELEASED'), ('ON-BOARDED', 'ON-BOARDED')], default='SELECTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Grade',
            field=models.CharField(choices=[('IS1', 'IS1'), ('IS2', 'IS2'), ('IS3', 'IS3'), ('IS4', 'IS4'), ('IS5', 'IS5'), ('IS6', 'IS6')], max_length=10),
        ),
    ]
